### ISSUE TITLE
Did anyone have problems with instantiating firebase and had to add stuff to build.gradle?

### ISSUE THREAD

**Issue by thandomy** [thandomy/foodie#8]
The app is not starting
I get:
   java.lang.IncompatibleClassChangeError: Class com.google.firebase.zza implements non-interface class com.google.android.gms.internal.zzabk (declaration of 'com.google.firebase.zza' appears in /data/app/com.team3009.foodie-2/split_l

**Comment by zansibanyoni** [comment]
No I did not get that error. Check if you have added anything from the time we presented to Terrence

**Comment by thandomy** [comment]
Fixed. I had a dependency that didnt work
